name: iiko Daily Margin ETL

on:
  workflow_dispatch:
    inputs:
      date_from:
        required: false
      date_to:
        required: false

  schedule:
    - cron: "0 4 * * *"   # каждый день в 07:00 по МСК

jobs:
  etl:
    runs-on: ubuntu-latest

    env:
      IIKO_BASE_URL: ${{ secrets.IIKO_BASE_URL }}
      IIKO_LOGIN: ${{ secrets.IIKO_LOGIN }}
      IIKO_PASSWORD: ${{ secrets.IIKO_PASSWORD }}

      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      PG_DB: ${{ secrets.PG_DB }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_SSLMODE: ${{ secrets.PG_SSLMODE }}

      DATE_FROM: ${{ github.event.inputs.date_from }}
      DATE_TO:   ${{ github.event.inputs.date_to }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt
      - run: python etl_iiko_margin_daily.py
